import { jsPDF } from 'jspdf';
import { ScanReport } from '../types/scan';

export function generateMedicalReportPDF(report: ScanReport, hospitalName = 'SmileScan Enterprise Hospital') {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Header Banner
  doc.setFillColor(37, 99, 235); // #2563EB Primary
  doc.rect(0, 0, 210, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('SMILESCAN AI DENTAL CLINIC', 14, 15);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Clinical Decision Support System | Medical Diagnostic Report', 14, 22);

  // Hospital Details
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(9);
  doc.text(`Facility: ${hospitalName}`, 140, 12);
  doc.text(`Report ID: #${report.id}`, 140, 17);
  doc.text(`Date: ${new Date(report.createdAt).toLocaleDateString()}`, 140, 22);

  // Section 1: Patient & Doctor Info Box
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 34, 182, 30, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('PATIENT DETAILS', 18, 42);
  doc.text('ATTENDING DOCTOR', 108, 42);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);

  doc.text(`Name: ${report.patientName}`, 18, 49);
  doc.text(`Patient ID: ${report.patientId}`, 18, 55);

  doc.text(`Doctor: ${report.doctorName}`, 108, 49);
  doc.text(`Specialization: Endodontics & AI Diagnostics`, 108, 55);

  // Section 2: AI Diagnostic Findings Summary
  let y = 72;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(37, 99, 235);
  doc.text('1. AI RADIOGRAPH DIAGNOSTIC SUMMARY', 14, y);
  y += 6;

  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, 182, 22, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(`Radiograph Type: ${report.imageType}`, 18, y + 7);
  doc.text(`Overall Severity: ${report.overallSeverity.toUpperCase()}`, 18, y + 15);

  doc.text(`Confidence Rating: ${report.overallConfidence}%`, 110, y + 7);
  doc.text(`Report Status: ${report.status}`, 110, y + 15);

  y += 28;

  // Section 3: Detected Pathologies & Recommendations
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(37, 99, 235);
  doc.text('2. DETECTED PATHOLOGIES & CLINICAL RECOMMENDATIONS', 14, y);
  y += 8;

  report.predictions.forEach((pred, index) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(`${index + 1}. ${pred.disease} (${pred.confidence}% Confidence)`, 18, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(71, 85, 105);
    
    // Tooth Numbers & Severity
    doc.text(`Affected Teeth (FDI): Teeth #${pred.affectedTeeth.join(', ')}  |  Severity: ${pred.severity}`, 18, y);
    y += 5;

    // Description
    const splitDesc = doc.splitTextToSize(`Observations: ${pred.description}`, 174);
    doc.text(splitDesc, 18, y);
    y += splitDesc.length * 4.5 + 2;

    // Recommended Treatment
    doc.setFont('helvetica', 'bold');
    doc.text('Recommended Treatments:', 18, y);
    y += 4.5;
    doc.setFont('helvetica', 'normal');
    pred.recommendedTreatment.forEach(treat => {
      doc.text(`• ${treat}`, 22, y);
      y += 4.5;
    });
    y += 2;

    // Prescribed Medicines
    if (pred.suggestedMedicines && pred.suggestedMedicines.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Prescribed Medications:', 18, y);
      y += 4.5;
      doc.setFont('helvetica', 'normal');
      pred.suggestedMedicines.forEach(med => {
        doc.text(`• ${med.name} (${med.dosage}) - ${med.duration}`, 22, y);
        y += 4.5;
      });
      y += 2;
    }

    // Home Care Remedies
    if (pred.homeRemedies && pred.homeRemedies.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Home Care & Patient Instructions:', 18, y);
      y += 4.5;
      doc.setFont('helvetica', 'normal');
      pred.homeRemedies.forEach(rem => {
        doc.text(`• ${rem}`, 22, y);
        y += 4.5;
      });
    }

    y += 6;
  });

  // Footer / Signature Section
  const footerY = 265;
  doc.setDrawColor(203, 213, 225);
  doc.line(14, footerY, 196, footerY);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text('This document is generated by SmileScan AI Decision Support System. Clinical judgment must accompany all outputs.', 14, footerY + 6);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text('Attending Practitioner Signature:', 130, footerY + 12);

  doc.setDrawColor(148, 163, 184);
  doc.line(130, footerY + 22, 196, footerY + 22);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`${report.doctorName}`, 130, footerY + 26);

  // Save PDF
  doc.save(`SmileScan_Report_${report.patientName.replace(/\s+/g, '_')}_${report.id}.pdf`);
}
